# These are supported funding model platforms

# github: rahulbordoloi # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: rahulbordoloi # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom: ['http://paypal.me/rahulbordoloi', 'https://commerce.coinbase.com/checkout/c2be6faa-ef33-40ea-9a18-6054fe6d75a0'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
